---

- name: Checking Hadoop installed or not
  yum:
    list: hadoop
  register: hadoop

- name: checking jdk is installed or not
  yum:
    list: jdk
  register: jdk

- name: Installing Hadoop
  command:
    cmd: rpm -ivh https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm --force
  when: (hadoop.results | length == 0)

- name: Installing Java (jdk)
  yum:
    name: "http://anfadmin.ucsd.edu/linux/RHEL/7/x86_64/jdk-8u171-linux-x64.rpm"
    state: present
    disable_gpg_check: yes
  when: (jdk.results | length == 0)
